# the product name for the original data products, e.g. ga_ls8cls9c_gm_cyear_3
product1=
# the product name for the new data products, if left out it will be set to the same as the original product name
product2=
# each tiff is based on a certain band, this value allows us to focus on specific tiff, or '*' for all. if left out will default to all
band=
# the year (4 digits, e.g. 2025), this value is used the the path for the data products
year=
# the version, this value is used the the path for the data products, e.g. '4-0-0'
version=
# The directory of the original data products, e.g. s3://dea-public-data/derivative/ga_ls8cls9c_gm_cyear_3/
product1_dir=
# The directory of the new data products, e.g. s3://dea-public-data-dev/derivative/ga_ls8cls9c_gm_cyear_3_test/
product2_dir=
# where the report will be written, if left out will default to ./reports
output_dir=