version: "3.6"

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=postgres
    expose:
      - 5432
    restart: always

  sandbox:
     image: geoscienceaustralia/sandbox:latest
     environment:
       - DB_HOSTNAME=postgres
       - DB_USERNAME=postgres
       - DB_PASSWORD=opendatacubepassword
       - DB_DATABASE=postgres
       - AWS_DEFAULT_REGION=ap-southeast-2
       - AWS_ACCESS_KEY_ID=fake_id
       - AWS_SECRET_ACCESS_KEY=fake_key
       - AWS_NO_SIGN_REQUEST=YES
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
     volumes:
       - .:/dea-notebooks

  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
        - METADATA_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml
        - PRODUCT_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/87ca056fa62900596cbf05612da9033fc763009c/workspaces/sandbox-products.csv
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
