version: "3.6"

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=postgres
    expose:
      - 5432
    restart: always

  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
