
#!/bin/bash
#PBS -P u46
#PBS -N extract
#PBS -q hugemem
#PBS -l ncpus=7
#PBS -l mem=1024GB
#PBS -l walltime=24:00:00
#PBS -l wd
#PBS -M vanessa.newey@ga.gov.au
#PBS -m abe

module use /g/data/v10/public/modules/modulefiles
module load parallel
module load dea
PYTHONPATH=/g/data/r78/datacube_stats:$PYTHONPATH

export LC_ALL=en_AU.utf8
export LANG=en_AU.utf8

parallel python delwp_ls_downloader2.py ::: {1..11},11
done;
wait;