name: "Setup tests"
description: "Set up database access and tests"

inputs:
  image:
    description: "Sandbox image to test against"
    required: false
    default: "stable"
  pull_image_optional:
    description: "Pull the image from ecr"
    required: false
    default: "true"
  copy_tidal_model:
    description: "Copy tidal model file from s3 bucket"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials
      if: $${{ inputs.copy_tidal_model == 'true' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::538673716275:role/github-actions-role-readonly
        aws-region: ap-southeast-2
        role-duration-seconds: 7200  # 2 hours

    - name: Copy tide modelling files with the AWS CLI
      if: $${{ inputs.copy_tidal_model == 'true' }}
      run: |
        aws s3 sync s3://dea-non-public-data/tide_models/tide_models/fes2014 tide_models/fes2014 > /dev/null
        aws s3 sync s3://dea-non-public-data/tide_models/tide_models/hamtide tide_models/hamtide > /dev/null
      shell: bash

    - name: Login to Amazon ECR Private
      id: login-ecr
      if: $${{ inputs.pull_image_optional == 'true' }}
      uses: aws-actions/amazon-ecr-login@v2

    - name: Pull dea-sandbox image from ECR
      if: $${{ inputs.pull_image_optional == 'true' }}
      run: |
        docker pull 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com/geoscienceaustralia/sandbox:${{ inputs.image }}
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::060378307146:role/github-actions-dea-notebooks--sandbox
        aws-region: ap-southeast-2
        role-duration-seconds: 7200  # 2 hours

    - name: Get Database Credentials
      run: |
        username_password=$(aws ssm get-parameter --name /dea-sandbox-eks/sandbox_reader/db.creds --with-decryption  --query Parameter.Value --output text)
        # If we need separate username/password they can be split as follows.
        # However exporting them to GitHub Environment variables will leave the Password in the Logs, if further steps aren't taken.
        # IFS=: read -r PGUSERNAME PGPASSWORD <<< $username_password
        # echo "PGUSERNAME=${PGUSERNAME}" >> $GITHUB_ENV
        # echo "PGPASSWORD=${PGPASSWORD}" >> $GITHUB_ENV
        echo DATACUBE_DB_URL=postgresql://${username_password}@localhost:5432/odc >> $GITHUB_ENV
      shell: bash

    - name: Open Port Forward to RDS
      run: |
        npx basti connect \
          --custom-target-vpc vpc-086904199e505c1f6 \
          --custom-target-host db-aurora-dea-sandbox-eks-1.cos5zfpkso9m.ap-southeast-2.rds.amazonaws.com \
          --custom-target-port 5432 \
          --local-port 5432 &
        # Wait until the connection comes up, but, if it doesn't, don't hang forever.
        npx wait-on --timeout 120000 --interval 1000 tcp:127.0.0.1:5432
        echo "PGPORT=5432" >> $GITHUB_ENV
        echo "PGHOST=localhost" >> $GITHUB_ENV
      shell: bash
