matrix:
- name: Markdown
  sources:
  - '**/*.md'
  - '**/*.rst'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_AU
  dictionary:
    wordlists:
    - .github/workflows/configs/spellcheck_wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
- name: python
  aspell:
    lang: en
    d: en_AU
  pipeline:
  - pyspelling.filters.python:
      strings: false
      comments: false
  sources:
  - Tools/dea_tools/*.py
