matrix:
- name: Markdown
  sources:
  - '**/*.md'
  - '**/*.rst'
  - '**/*.py'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/workflows/configs/spellcheck_wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
