name: Python Lint
on:
  pull_request:
    paths:
    - '**.ipynb'
    - '**.py'
  workflow_dispatch:
  push:
    paths:
#    - '**.ipynb'
#    - '**.py'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install ruff
      - run: ruff check --output-format=github .

  bandit:
    runs-on: ubuntu-latest
    steps:
        - name: Perform Bandit Analysis
          uses: PyCQA/bandit-action@v1
    