name: Doc QA
on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

  workflow_dispatch:

jobs:
  pyspellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
        with:
          config_path: .github/workflows/configs/spellcheck_config.yaml