name: Test Modified Files

on:
  push:
    branches: [ changed_files ]
  pull_request:
    branches: [ changed_files ]

jobs:
  test_files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'

    - name: Get changed notebook files
      id: changed-notebooks
      uses: tj-actions/changed-files@v44
      with:
        files: '**/*.ipynb'
        separator: ' '
    
    - name: Print changed notebook files
      if: steps.changed-notebooks.outputs.any_changed == 'true'
      run: |
        echo "Changed notebook files:"
        echo "${{ steps.changed-notebooks.outputs.all_changed_files }}"
    
    - name: Get changed Python files
      id: changed-py-files
      uses: tj-actions/changed-files@v44
      with:
        files: '**/*.py'
        separator: ' '
    
    - name: Print changed Python files
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        echo "Changed Python files:"
        echo "${{ steps.changed-py-files.outputs.all_changed_files }}"
    
    # - name: Run pytest on Python files
    #   if: steps.changed-py-files.outputs.any_changed == 'true'
    #   run: |
    #     pytest Tests/dea_tools
